# Generated by Django 5.0.4 on 2024-04-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ti', models.IntegerField()),
                ('tj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Czynnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_event', to='CPM.zdarzenie')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_event', to='CPM.zdarzenie')),
            ],
        ),
    ]
