# Generated by Django 5.0.4 on 2024-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPM', '0002_cpm_zdarzenie_float_value_alter_zdarzenie_ti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnosc',
            name='after',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='czynnosc',
            name='before',
            field=models.IntegerField(),
        ),
    ]
